@id = e5bd3ae7-52d1-4ded-913a-d19b88c2bb1b
put http://localhost:5230/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine 48",
    "description": "Vegan everything! Join us for a healthy breakfast.",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}